### ISSUE TITLE
Fails to build on Qt5.12.1 MinGW73_64

### ISSUE THREAD

**Issue by shujaatak** [hostilefork/thinker-qt#7]
I get a lot of errors including but not limited to:

```
C:\test\thinker-qt-master\include\thinkerqt\thinkerrunner.h:212: error: invalid use of incomplete type 'class ThinkerBase'
             QThread::currentThread() == _runner.getThinker().thread(),
                                         ~~~~~~~~~~~~~~~~~~^~
```
Can you please see if this can be solved.

**Comment by hostilefork** [comment]
Haven't looked at this code in many years (!) but I will see what I can do.  The compilers have changed a lot .

I addressed the other warnings/issues tonight, but this one you mention doesn't seem to have an obvious reason as to why it stopped working.  I'll see if I can create a minimal case tomorrow.

**Comment by shujaatak** [comment]
thinker-qt seems awesome library. Hopefully it would see many many years more. :)

**Comment by hostilefork** [comment]
Thanks--well it would be great if someone were actively using it!  I'm busy with other stuff these days, but it's worth it to have it working in a modern Qt...so...

I found the problem for that error.  It seems something changed about the Meta-Object-Compiler so that I can't get away with a recursive include here:

https://github.com/hostilefork/thinker-qt/blob/2c16c17650ae0108c89e49a631ccf0992ca22c1f/include/thinkerqt/thinker.h#L404

thinkermanager.h includes thinker.h.  Previously that wasn't a problem, because there's an #ifdef include guard, so even though it's in the process of compiling thinker.h the second include has no effect.  I can't tell exactly *why* that pattern is breaking today's moc (?), but it does.

I've sorted that out by splitting thinker.h into two files...thinkerbase.h and thinker.h, where thinkermanager.h just includes thinkerbase.h.  But seems there are some runtime problems preventing the mandelbrot sample from working.  I'm looking at those now, hopefully I can figure out what's going on relatively quickly...will let you know once it's fixed.

**Comment by shujaatak** [comment]
Not important but wondering how you would have figured out that the issue was the recursive include.
That's amazing!

**Comment by hostilefork** [comment]
The most important element of problem solving: the "Minimal, Complete, Verifiable Example" or "MCVE" (though it has many other names)...

https://stackoverflow.com/help/minimal-reproducible-example

I commented out all the implementation files, and removed all members from ThinkerManager...until I found that even a completely empty ThinkerManager had the problem.  I then compared this to a very simple class which was started in a new project.  It quickly became clear the include structure was the difference.

**Comment by shujaatak** [comment]
I am highly thankful to you for providing so much good information, you are so generous! 
By the way, I was away, so could not respond in timely fashion.

**Comment by hostilefork** [comment]
Ok...got around to looking at getting this to work today.  The Mandelbrot sample should now run, please let me know if it does not.

The biggest issue was a QTimer issue, where you seem to no longer be able to issue QTimer::start() calls from any thread other than the one that the QTimer's affinity is for.  That creates some hassle for a Thinker, because it wants to run in a tight loop doing updates...but have a `SignalThrottler` that makes it so the GUI thread doesn't get notified too frequently of those updates.  Hence it was expecting to be able to set timers from that thread.

Changing the QTimer's thread affinity seems easy but then it had to match that of the SignalThrottler, and the throttler was trying to do some tricks to avoid a QMutex.  Those tricks may or may not be able to be made to work...but in any case, I tried to simplify the code so perhaps it can be looked at with suggestions for improvement.

See the commits for notes on things changed  Definitely interested in any feedback you might have, would be neat to see someone else getting it to work for something.

**Comment by shujaatak** [comment]
Amazing! It works now!
I had to include QDebug in signalthrottler.cpp to compile it successfully.

`#include <QDebug>`

**Comment by hostilefork** [comment]
Yay!  Great.  That was just a mistake in pushing what to commit, debug code is removed here:

https://github.com/hostilefork/thinker-qt/commit/43c7a8a8646cea612c0b66d59c724b0a1ad7117d

Looking forward to any insights you might have, feel free to send PRs!
